import { contact } from './expo-contact.js';
const direct = document.querySelector('#direct-contact');
const message = 'Hola Fabrizzio, vi tu portfolio de Exhibition & Digital Design. Quiero conversar sobre un proyecto para mi empresa.';
if (/^\d{8,15}$/.test(contact.whatsapp)) { const a=document.createElement('a'); a.className='button primary';a.href='https://wa.me/'+contact.whatsapp+'?text='+encodeURIComponent(message);a.textContent='Escríbeme por WhatsApp';a.insertAdjacentHTML('beforeend','<svg class="icon icon-forward-doodle" viewBox="0 0 24 24" aria-hidden="true"><path d="M3.5 5.3c2.2 2 4.4 4.1 6.8 6.7-2.3 2.5-4.6 4.7-6.7 6.8M10.7 5.2c2.3 2.1 4.5 4.2 6.8 6.8-2.4 2.5-4.6 4.6-6.7 6.7M19 5.4c-.1 2.2.1 4.4 0 6.6.1 2.3-.1 4.5 0 6.7"/></svg>');direct.replaceChildren(a);document.querySelector('.sticky').href=a.href; }
if (contact.email && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(contact.email)){const a=document.createElement('a');a.className='button';a.href='mailto:'+contact.email;a.textContent=contact.email;if(!contact.whatsapp)direct.replaceChildren(a);else direct.append(a);}
document.querySelector('#copy-brief').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(document.querySelector('#brief').value);document.querySelector('#copy-status').textContent='Mensaje copiado.';}catch{document.querySelector('#brief').select();document.querySelector('#copy-status').textContent='Selecciona y copia el mensaje.';}});
document.querySelector('#load-viewer').addEventListener('click',async(event)=>{event.target.disabled=true;document.querySelector('#viewer-status').textContent='Cargando visualizador…';try{await import('@google/model-viewer');const viewer=document.createElement('model-viewer');for(const [key,value]of Object.entries({src:'/expo/assets/model.glb','ios-src':'/expo/assets/model.usdz',alt:'Propuesta no construida del stand Gestecner Navegestic',ar:'','ar-modes':'webxr scene-viewer quick-look','camera-controls':'','shadow-intensity':'1',exposure:'0.9'}))viewer.setAttribute(key,value);const ar=document.createElement('button');ar.slot='ar-button';ar.className='button primary ar-button';ar.textContent='Ver en tu espacio';ar.insertAdjacentHTML('beforeend','<svg class="icon icon-forward-doodle" viewBox="0 0 24 24" aria-hidden="true"><path d="M3.5 5.3c2.2 2 4.4 4.1 6.8 6.7-2.3 2.5-4.6 4.7-6.7 6.8M10.7 5.2c2.3 2.1 4.5 4.2 6.8 6.8-2.4 2.5-4.6 4.6-6.7 6.7M19 5.4c-.1 2.2.1 4.4 0 6.6.1 2.3-.1 4.5 0 6.7"/></svg>');viewer.append(ar);viewer.addEventListener('error',()=>{const fallback=document.createElement('p');fallback.textContent='No se pudo cargar el modelo. Revisa tu conexión e intenta nuevamente.';document.querySelector('#viewer-shell').replaceChildren(fallback);});document.querySelector('#viewer-shell').replaceChildren(viewer);}catch{document.querySelector('#viewer-status').textContent='No se pudo cargar. Comprueba tu conexión y vuelve a intentar.';event.target.disabled=false;}});

const imageDialog=document.querySelector('#image-dialog');document.querySelectorAll('[data-image]').forEach(button=>button.addEventListener('click',()=>{document.querySelector('#dialog-image').src=button.dataset.image;document.querySelector('#dialog-image').alt=button.dataset.caption;document.querySelector('#dialog-caption').textContent=button.dataset.caption;imageDialog.showModal();}));document.querySelector('#close-image').addEventListener('click',()=>imageDialog.close());imageDialog.addEventListener('click',event=>{if(event.target===imageDialog){const rect=imageDialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)imageDialog.close();}});
