// English is the editable source in content.js. These overrides provide the
// complete visitor-facing Spanish and Portuguese versions.
export const locales = {
  es: {
    copy: {
      navigation: { work: 'Proyectos', services: 'Servicios', lab: 'Lab', about: 'Sobre mí', contact: 'Contacto', startProject: 'Hablemos de tu proyecto', playlist: 'Mi playlist' },
      home: {
        role: 'Diseñador visual independiente', location: 'Desde Paraguay · Para todo el mundo',
        hero: { line1: 'Diseño cosas', line2: 'que la gente ', accent: 'recuerda.' },
        intro: 'Diseño visual y experiencias físicas moldeados por experiencia internacional, desde una práctica independiente y enfocada.', exploreWorkButton: 'Ver proyectos',
        playlist: { kicker: 'FR / EN REPRODUCCIÓN', title: 'Mi playlist', open: 'Abrir en Spotify' },
        album: { kicker: 'Álbum de proyectos', projectLink: 'Explorar proyectos', pause: 'Pausar movimiento', play: 'Activar movimiento' },
        showcase: { bigWords: ['FORMA', 'CON', 'PROPÓSITO'], middleLabel: 'DIGITAL / FÍSICO / HUMANO', rightLabel: 'EXPERIENCIAS VISUALES', caption: 'Un espacio para proyectos, ideas y lo que viene.' },
        work: { kicker: '01 / Proyectos seleccionados', title: { line1: 'Trabajo que habla', accent: 'por sí mismo.' }, allWorkLink: 'Todos los proyectos', placeholderNote: 'Las imágenes y detalles de los casos son ilustrativos hasta añadir material aprobado.' },
        services: { kicker: '02 / Lo que hago', title: { line1: 'Muchas herramientas.', accent: 'Una visión clara.' } },
        approach: { kicker: '03 / Mi enfoque', title: { line1: 'El buen diseño se ve bien.', accent: 'El gran diseño hace más.' }, body: 'Uno el oficio visual con el pensamiento práctico, desde la primera pregunta hasta la experiencia final.', moreLink: 'Más sobre mí' },
        lab: { kicker: 'Ideas en proceso', title: { line1: 'La curiosidad es', line2: 'parte del trabajo.' }, body: 'Artículos, casos y experimentos sobre diseño, nuevas tecnologías e IA.', link: 'Explorar el Lab' },
      },
      work: { kicker: 'Portafolio / Proyectos seleccionados', title: { line1: 'Hecho para', accent: 'generar impacto.' }, intro: 'Trabajo de marca, digital y espacial. Estos proyectos son vistas preliminares hasta aprobar los casos y las imágenes finales.', guidanceTitle: 'Un buen caso muestra', guidanceBody: 'El encargo. El desafío. Las decisiones. El resultado. Cada página contará esa historia con materiales reales y mi rol claramente acreditado.' },
      services: { kicker: 'Servicios / Formas de colaborar', title: { line1: 'El diseño indicado', line2: 'para el ', accent: 'proyecto indicado.' }, intro: 'Experiencia internacional con una forma de trabajo directa e independiente. Definimos el alcance adecuado para tus objetivos y presupuesto.', monthlyKicker: 'Apoyo continuo', monthlyTitle: 'Colaboración mensual de diseño.', monthlyBody: 'Para equipos con necesidades de diseño recurrentes. Definimos el formato, la capacidad y el alcance mensual antes de comenzar.', monthlyButton: 'Consultar disponibilidad', note: 'Los precios se ajustan al alcance y a la eficiencia de una práctica independiente.' },
      about: { kicker: 'Sobre mí / Fabrizzio Ruiz', title: { line1: 'Diseño entre', accent: 'disciplinas.' }, intro: 'Soy diseñador visual en Asunción, Paraguay, y colaboro con marcas y equipos de distintos países.', sectionKicker: 'Un poco sobre mí', sectionTitle: { line1: 'Una perspectiva.', line2: 'Muchas formas de hacerla real.' }, paragraph1: 'Mi práctica abarca identidad de marca, sitios web, campañas y espacios físicos. En cada formato busco la idea que vuelve al trabajo claro, distintivo y útil.', paragraph2: 'Trabajar en el exterior moldeó los estándares que aplico a cada proyecto, desde la calidad del diseño hasta la comunicación y la entrega. Desde Paraguay mantengo una colaboración directa y flexible con equipos de cualquier lugar.', contactLink: 'Trabajemos juntos', portraitPlaceholder: 'Retrato próximamente' },
      lab: { kicker: 'Fabrizzio / Lab', title: { line1: 'Un lugar para', accent: 'probar ideas.' }, intro: 'Notas en la intersección del diseño, la tecnología y la IA. Lo que hago, lo que aprendo y lo que resulta útil.', categoriesKicker: 'Lo que encontrarás aquí', categories: [ { number: '01 / Escritura', title: 'Artículos', body: 'Ideas sobre diseño visual, trabajo creativo y las herramientas que transforman ambos.' }, { number: '02 / En práctica', title: 'Casos de uso', body: 'Procesos reales y problemas concretos, con las decisiones detrás del resultado.' }, { number: '03 / En proceso', title: 'Experimentos', body: 'Prototipos, pruebas y aprendizajes de lo que funciona y lo que no.' } ], latestKicker: 'Lo último del Lab', latestTitle: { line1: 'Trabajo en proceso.', accent: 'Ideas en voz alta.' }, emptyKicker: 'Primeras notas en proceso', emptyTitle: 'Las ideas mejoran cuando se prueban y comparten.', emptyBody: 'Los primeros artículos y experimentos aparecerán aquí. Este será su espacio.', exploringKicker: 'Explorando ahora', exploring: ['Flujos de exhibición con IA', 'Herramientas de diseño sensibles a la marca', 'Experiencias web creativas'], exploringNote: 'Son temas en exploración, no casos publicados.' },
      contact: { kicker: 'Contacto / Nuevos proyectos', title: { line1: 'Cuéntame qué', line2: 'estás ', accent: 'creando.' }, intro: 'Comparte algunos detalles y te responderé con el mejor próximo paso.', emailLabel: '¿Prefieres escribir?', emailMissing: 'Correo pendiente de añadir antes del lanzamiento', form: { name: 'Tu nombre', namePlaceholder: 'Tu nombre', email: 'Correo electrónico', emailPlaceholder: 'tu@empresa.com', company: 'Empresa / organización', optional: 'Opcional', projectType: '¿Qué necesitas?', projectTypePlaceholder: 'Elige un tipo de proyecto', projectTypes: ['Marca y campañas', 'Web y digital', 'Expos y espacios', 'Colaboración mensual de diseño', 'Otra cosa'], budget: 'Presupuesto aproximado', budgetPlaceholder: 'Elige un rango (opcional)', budgetRanges: ['Menos de $2.500', '$2.500–$5.000', '$5.000–$10.000', 'Más de $10.000', 'Aún no lo sé'], timeline: 'Plazo ideal', timelinePlaceholder: '¿Cuándo te gustaría empezar?', message: 'Cuéntame sobre tu proyecto', messagePlaceholder: '¿Qué estás creando y cómo sería un buen resultado?', submit: 'Preparar correo' } },
      footer: { kicker: '¿Tienes un proyecto en mente?', title: { line1: 'Hagamos que', accent: 'importe.' }, descriptor: 'Diseñador visual independiente', worldwide: 'Trabajo internacional' },
    },
    services: [
      { title: 'Marca y campañas', homeBody: 'Identidades, lanzamientos y piezas creativas que hacen reconocible una marca.', body: 'Identidades, conceptos de campaña y piezas visuales para comunicar con consistencia.', items: ['Dirección e identidad de marca', 'Creatividad para campañas', 'Piezas digitales e impresas'] },
      { title: 'Web y digital', homeBody: 'Sitios y experiencias digitales creados con claridad e impacto.', body: 'Sitios y landing pages que causan una gran primera impresión y orientan a la acción.', items: ['Dirección visual web', 'Diseño de landing pages', 'Sistemas de diseño digital'] },
      { title: 'Expos y espacios', homeBody: 'Experiencias visuales que llevan la marca al mundo físico.', body: 'Experiencias de marca para encuentros reales, del concepto a la dirección visual lista para producir.', items: ['Conceptos de exhibición', 'Gráfica ambiental', 'Dirección de experiencias'] },
    ],
    projects: [
      { label: 'Identidad de marca', title: 'Una marca hecha para recordar.', note: 'Proyecto destacado provisional' },
      { label: 'Web y digital', title: 'Una experiencia digital más clara.', note: 'Proyecto digital provisional' },
      { label: 'Experiencial', title: 'Un espacio para entrar y sentir.', note: 'Proyecto espacial provisional' },
    ],
    heroCovers: [ { title: 'Identidad de marca', category: 'Proyecto provisional' }, { title: 'Experiencia digital', category: 'Proyecto provisional' }, { title: 'Diseño de exhibición', category: 'Proyecto provisional' }, { title: 'Diseño de campañas', category: 'Proyecto provisional' }, { title: 'Sistemas visuales', category: 'Proyecto provisional' }, { title: 'Nuevo proyecto', category: 'Proyecto provisional' } ],
    ui: { select: 'Seleccionar', coverInstructions: 'Portadas de proyectos. Usa las flechas, la rueda o arrastra para explorar.', portfolioSlot: 'ESPACIO DE PORTAFOLIO', illustrative: 'Composición ilustrativa para un futuro caso de', service: 'SERVICIO', inquire: 'Consultar sobre', notFound: 'PÁGINA NO ENCONTRADA', notFoundTitle: 'Aquí todavía<br/><em>no hay nada.</em>', backHome: 'Volver al inicio ↗', emailSetup: 'Aún no hay un correo configurado. Añádelo en src/content.js antes del lanzamiento.', emailPrepared: 'Se abrirá tu aplicación de correo con un mensaje preparado. Envíalo allí para completar la consulta.', contactPage: 'Ir a contacto', previousCover: 'Portada anterior', nextCover: 'Portada siguiente', openMenu: 'Abrir menú', closeMenu: 'Cerrar menú' },
  },
  pt: {
    copy: {
      navigation: { work: 'Projetos', services: 'Serviços', lab: 'Lab', about: 'Sobre mim', contact: 'Contato', startProject: 'Vamos conversar', playlist: 'Minha playlist' },
      home: {
        role: 'Designer visual independente', location: 'Do Paraguai · Para o mundo',
        hero: { line1: 'Crio designs', line2: 'que as pessoas ', accent: 'notam.' },
        intro: 'Design visual e experiências físicas moldados pela experiência internacional, em uma prática independente e focada.', exploreWorkButton: 'Ver projetos',
        playlist: { kicker: 'FR / TOCANDO AGORA', title: 'Minha playlist', open: 'Abrir no Spotify' },
        album: { kicker: 'Álbum de projetos', projectLink: 'Explorar projetos', pause: 'Pausar movimento', play: 'Ativar movimento' },
        showcase: { bigWords: ['FORMA', 'COM', 'PROPÓSITO'], middleLabel: 'DIGITAL / FÍSICO / HUMANO', rightLabel: 'EXPERIÊNCIAS VISUAIS', caption: 'Um espaço para projetos, ideias e o que vem a seguir.' },
        work: { kicker: '01 / Projetos selecionados', title: { line1: 'Trabalho que fala', accent: 'por si só.' }, allWorkLink: 'Todos os projetos', placeholderNote: 'As imagens e detalhes dos cases são ilustrativos até a inclusão de materiais aprovados.' },
        services: { kicker: '02 / O que faço', title: { line1: 'Muitas ferramentas.', accent: 'Uma visão clara.' } },
        approach: { kicker: '03 / Minha abordagem', title: { line1: 'Bom design é bonito.', accent: 'Ótimo design vai além.' }, body: 'Uno habilidade visual e pensamento prático, da primeira pergunta à experiência final.', moreLink: 'Mais sobre mim' },
        lab: { kicker: 'Ideias em andamento', title: { line1: 'A curiosidade faz', line2: 'parte do trabalho.' }, body: 'Artigos, casos e experimentos sobre design, novas tecnologias e IA.', link: 'Explorar o Lab' },
      },
      work: { kicker: 'Portfólio / Projetos selecionados', title: { line1: 'Feito para', accent: 'causar impacto.' }, intro: 'Trabalhos de marca, digital e espaços. Estes projetos são prévias até a aprovação dos cases e imagens finais.', guidanceTitle: 'Um bom case mostra', guidanceBody: 'O briefing. O desafio. As escolhas. O resultado. Cada página contará essa história com materiais reais e meu papel claramente creditado.' },
      services: { kicker: 'Serviços / Formas de trabalhar juntos', title: { line1: 'O design certo', line2: 'para o ', accent: 'projeto certo.' }, intro: 'Experiência internacional com uma forma de trabalho direta e independente. Definimos o escopo certo para seus objetivos e orçamento.', monthlyKicker: 'Apoio contínuo', monthlyTitle: 'Parceria mensal de design.', monthlyBody: 'Para equipes com necessidades recorrentes de design. Definimos o formato, a capacidade e o escopo mensal antes de começar.', monthlyButton: 'Consultar disponibilidade', note: 'Os preços acompanham o escopo e a eficiência de uma prática independente.' },
      about: { kicker: 'Sobre mim / Fabrizzio Ruiz', title: { line1: 'Design entre', accent: 'disciplinas.' }, intro: 'Sou designer visual em Assunção, Paraguai, e trabalho com marcas e equipes de vários países.', sectionKicker: 'Um pouco sobre mim', sectionTitle: { line1: 'Uma perspectiva.', line2: 'Muitas formas de torná-la real.' }, paragraph1: 'Minha prática transita entre identidade de marca, sites, campanhas e espaços físicos. Em cada formato, busco a ideia que torna o trabalho claro, distinto e útil.', paragraph2: 'Trabalhar no exterior moldou os padrões que aplico a cada projeto, da qualidade do design à comunicação e à entrega. A partir do Paraguai, mantenho uma colaboração direta e flexível com equipes de qualquer lugar.', contactLink: 'Vamos trabalhar juntos', portraitPlaceholder: 'Retrato em breve' },
      lab: { kicker: 'Fabrizzio / Lab', title: { line1: 'Um lugar para', accent: 'testar ideias.' }, intro: 'Notas na interseção de design, tecnologia e IA. O que crio, o que aprendo e o que se mostra útil.', categoriesKicker: 'O que você encontrará aqui', categories: [ { number: '01 / Escrita', title: 'Artigos', body: 'Ideias sobre design visual, trabalho criativo e as ferramentas que transformam ambos.' }, { number: '02 / Na prática', title: 'Casos de uso', body: 'Processos reais e problemas específicos, com as decisões por trás do resultado.' }, { number: '03 / Em andamento', title: 'Experimentos', body: 'Protótipos, testes e lições úteis do que funciona e do que não funciona.' } ], latestKicker: 'Novidades do Lab', latestTitle: { line1: 'Trabalho em andamento.', accent: 'Ideias em voz alta.' }, emptyKicker: 'Primeiras notas em andamento', emptyTitle: 'Ideias ficam melhores quando são testadas e compartilhadas.', emptyBody: 'Os primeiros artigos e experimentos aparecerão aqui. Este será o espaço deles.', exploringKicker: 'Explorando agora', exploring: ['Fluxos de exposição com IA', 'Ferramentas de design sensíveis à marca', 'Experiências web criativas'], exploringNote: 'Estes são temas em exploração, não cases publicados.' },
      contact: { kicker: 'Contato / Novos projetos', title: { line1: 'Conte o que', line2: 'você está ', accent: 'criando.' }, intro: 'Compartilhe alguns detalhes e retornarei com o melhor próximo passo.', emailLabel: 'Prefere escrever?', emailMissing: 'E-mail a ser adicionado antes do lançamento', form: { name: 'Seu nome', namePlaceholder: 'Seu nome', email: 'Endereço de e-mail', emailPlaceholder: 'voce@empresa.com', company: 'Empresa / organização', optional: 'Opcional', projectType: 'O que você precisa?', projectTypePlaceholder: 'Selecione o tipo de projeto', projectTypes: ['Marca e campanhas', 'Web e digital', 'Expos e espaços', 'Parceria mensal de design', 'Outro'], budget: 'Orçamento aproximado', budgetPlaceholder: 'Selecione uma faixa (opcional)', budgetRanges: ['Abaixo de US$ 2.500', 'US$ 2.500–5.000', 'US$ 5.000–10.000', 'Acima de US$ 10.000', 'Ainda não sei'], timeline: 'Prazo ideal', timelinePlaceholder: 'Quando gostaria de começar?', message: 'Conte sobre seu projeto', messagePlaceholder: 'O que está criando e como seria um bom resultado?', submit: 'Preparar e-mail' } },
      footer: { kicker: 'Tem um projeto em mente?', title: { line1: 'Vamos fazer', accent: 'valer a pena.' }, descriptor: 'Designer visual independente', worldwide: 'Trabalho internacional' },
    },
    services: [
      { title: 'Marca e campanhas', homeBody: 'Identidades, lançamentos e peças criativas que tornam a marca reconhecível.', body: 'Identidades, conceitos de campanha e peças visuais para uma presença consistente.', items: ['Direção e identidade de marca', 'Criatividade para campanhas', 'Peças digitais e impressas'] },
      { title: 'Web e digital', homeBody: 'Sites e experiências digitais criados com clareza e impacto.', body: 'Sites e landing pages que causam uma ótima primeira impressão e orientam à ação.', items: ['Direção visual para sites', 'Design de landing pages', 'Sistemas de design digital'] },
      { title: 'Expos e espaços', homeBody: 'Experiências visuais que levam a marca ao mundo físico.', body: 'Experiências de marca para encontros reais, do conceito à direção visual pronta para produção.', items: ['Conceitos de exposição', 'Gráfica ambiental', 'Direção de experiências'] },
    ],
    projects: [
      { label: 'Identidade de marca', title: 'Uma marca feita para ser lembrada.', note: 'Projeto em destaque provisório' },
      { label: 'Web e digital', title: 'Uma experiência digital mais clara.', note: 'Projeto digital provisório' },
      { label: 'Experiencial', title: 'Um espaço para entrar e sentir.', note: 'Projeto espacial provisório' },
    ],
    heroCovers: [ { title: 'Identidade de marca', category: 'Projeto provisório' }, { title: 'Experiência digital', category: 'Projeto provisório' }, { title: 'Design de exposição', category: 'Projeto provisório' }, { title: 'Design de campanhas', category: 'Projeto provisório' }, { title: 'Sistemas visuais', category: 'Projeto provisório' }, { title: 'Novo projeto', category: 'Projeto provisório' } ],
    ui: { select: 'Selecionar', coverInstructions: 'Capas de projetos. Use as setas, a roda do mouse ou arraste para explorar.', portfolioSlot: 'ESPAÇO DE PORTFÓLIO', illustrative: 'Composição ilustrativa para um futuro case de', service: 'SERVIÇO', inquire: 'Consultar sobre', notFound: 'PÁGINA NÃO ENCONTRADA', notFoundTitle: 'Ainda não há<br/><em>nada aqui.</em>', backHome: 'Voltar ao início ↗', emailSetup: 'O e-mail ainda não foi configurado. Adicione em src/content.js antes do lançamento.', emailPrepared: 'Seu aplicativo de e-mail deve abrir com uma mensagem pronta. Envie-a para concluir o contato.', contactPage: 'Ir para contato', previousCover: 'Capa anterior', nextCover: 'Próxima capa', openMenu: 'Abrir menu', closeMenu: 'Fechar menu' },
  },
};
